<?php
/**
 * Created by PhpStorm.
 * User: USER
 * Date: 20.12.2018
 * Time: 18:44
 */

namespace app\components;


use yii\helpers\Html;
use yii\base\Component;


class MessengerComponent extends Component
{
    public $message;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub обязательно вызывать перед своими изменениями
        //можно произвести какие-либо действия при инициализации компонента
        $this->message = "Текст сообщения";

    }

    public function displayHTMLMessage($userMessage) {

        $this->message=$userMessage;

        return Html::encode($this->message);
    }

}