<?php
/**
 * Created by PhpStorm.
 * User: USER
 * Date: 19.12.2018
 * Time: 10:25
 */
namespace app\models;


class ActivityForm extends Activity
{
     public $email; //этого поля нет в таблице базы данных
    ///////////////////registration
//    public $login;
//    public $user_name;
//    public $password;
//    public $password_repeat;
//    public $accept_process_data;

    public function rules() //служебная ф-ция, содержит правила валидации атрибутов модели
    {

        return array_merge([

            ['title','required'],
            ['title','string','length'=>[5,10]],
            [['title','body'],'trim'],               // убирает ненужны пробелы сбоку
            ['body','string','max'=>500],
            //['title',FormValidator::class],       //не знаю, как указать use  для FormValidator
            [['date_start','date_end'],'date','format'=>'php:Y-m-d H:i:s'],

            ['email','email'],
            ['email','required','when'=>function($model,$attribute){
                return empty($model->body)?false:true;}],

            ['is_block','boolean'],

            //[['login','password'],'required'],
           // ['login','string','length'=>[5,10]],
            //['password','match','pattern'=> '/^[a-z]{5,19}/','message'=>'Пароль на латинице не менее 5 символов'],
            //['password_repeat','compare','compareAttribute' => 'password'],
            //['accept_process_data','boolean'],

        ],parent::rules());
    }

    public function beforeValidate()
    {
        if($this->date_start) {
            $date = \DateTime::createFromFormat('Y-m-d H:i:s', $this->date_start);
            if(!$date){
                return parent::beforeValidate();
            }
            $this->date_start = $date->format('Y-m-d H:i:s');
        }
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return [
            'title'=>'Наименование',
            'date_start'=>'Дата начала',
            'date_end'=>'Дата окончания',
            'user_id'=>'ID автора',
            'day_id'=>'День календаря',
            'body'=>'Описание',
            'email'=>'Email',
            'address'=>'Адрес проведения мероприятия',
            'is_block'=>'Событие заблокировано'

            //'login'=>'Введите логин',
            //'date_created'=>'Дата регистрации',
            //'password'=>'Пароль',
            //'accept_process_data'=>'Согласие на обработку персональных данных'
        ];
    }
}