<?php
/**
 * Created by PhpStorm.
 * User: USER
 * Date: 19.12.2018
 * Time: 10:25
 */
namespace app\models;
use app\models\validators\FormValidator;


class ActivityForm extends Activity
{
     public $email; //этого поля нет в таблице базы данных


    public function rules() //служебная ф-ция, содержит правила валидации атрибутов модели
    {

        return array_merge([

            [['title','email'],'required'],
            ['title','string','length'=>[5,20]],
            [['title','body'],'trim'],               // убирает ненужные пробелы сбоку
            ['body','string','max'=>500],
            [['title','body'],FormValidator::class],     //подключаем автономный валидатор
            [['date_start','date_end'],'date','format'=>'php:Y-m-d H:i:s'],

            ['email','email'],
            ['email','required','when'=>function($model,$attribute){
                return empty($model->body)?false:true;}],

            ['is_block','boolean'], //для checkbox


        ],parent::rules());
    }

    public function beforeValidate()
    {
        if($this->date_start) {
            $date = \DateTime::createFromFormat('Y-m-d H:i:s', $this->date_start);
            if(!$date){
                return parent::beforeValidate();
            }
            $this->date_start = $date->format('Y-m-d H:i:s');
        }
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return [
            'title'=>'Наименование',
            'date_start'=>'Дата начала',
            'date_end'=>'Дата окончания',
            'user_id'=>'ID автора',
            'day_id'=>'День календаря',
            'body'=>'Описание',
            'email'=>'Email',
            'address'=>'Адрес проведения мероприятия',
            'is_block'=>'Событие заблокировано',
            'comment'=>'Заполните форму в соответствии с правилами',

        ];
    }
}