<?php
/**
 * Created by PhpStorm.
 * User: USER
 * Date: 19.12.2018
 * Time: 10:25
 */
namespace app\models;


class EventForm extends Events
{

    public function rules() //служебная ф-ция, содержит правила валидации атрибутов модели
    {

        return array_merge([

            ['title','required'],
            ['title','string','length'=>[5,255]],
            [['title','body'],'trim'],               // убирает ненужны пробелы сбоку
            ['body','string','max'=>500]

        ],parent::rules());
    }

    public function beforeValidate()
    {
       // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return [
            'title'=>'Наименование',
            'day_id'=>'День календаря',
            'body'=>'Описание',
        ];
    }
}